
/*
INSERT INTO USER (ID, NAME) VALUES (1, 'JOHN');
INSERT INTO USER (ID, NAME) VALUES (2, 'ROSE');
INSERT INTO USER (ID, NAME) VALUES (3, 'BEN');
INSERT INTO USER (ID, NAME) VALUES (4, 'RACHEL');

INSERT INTO TOPIC (ID, SEEKER_ID, HELPER_ID, DESC) VALUES(100, 1, 2, 'TEST TOPIC 1');
INSERT INTO TOPIC (ID, SEEKER_ID, HELPER_ID, DESC) VALUES(200, 2, 3, 'TEST TOPIC 2');
INSERT INTO TOPIC (ID, SEEKER_ID, HELPER_ID, DESC) VALUES(300, 3, 4, 'TEST TOPIC 3');

INSERT INTO CHAT_INFO (ID, HELPER_ID, SEEKER_ID, TOPIC_ID) VALUES
    (51, 1, 2, 100);
INSERT INTO CHAT_INFO (ID, HELPER_ID, SEEKER_ID, TOPIC_ID) VALUES
    (52, 1, 3, 200);
INSERT INTO CHAT_INFO (ID, HELPER_ID, SEEKER_ID, TOPIC_ID) VALUES
    (53, 4, 1, 300);

INSERT INTO CHAT (ID, CHAT_INFO_ID, CHAT_TEXT, CHATTER_ID, TIME_STAMP) VALUES
    (151, 51, 'HI ROSE', 1, '2021-10-16T05:00:00.000');
INSERT INTO CHAT (ID, CHAT_INFO_ID, CHAT_TEXT, CHATTER_ID, TIME_STAMP) VALUES
    (152, 51, 'HI JOHN', 2, '2021-10-16T05:01:00.000');
INSERT INTO CHAT (ID, CHAT_INFO_ID, CHAT_TEXT, CHATTER_ID, TIME_STAMP) VALUES
    (153, 51, 'HOWS LIFE ROSE?', 1, '2021-10-16T05:02:00.000');

*/